[package]
name = "trace-top"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
crossterm = "0.29.0"
hex = "0.4.3"
jiff = { version = "0.2", default-features = false, features = ["std", "tz-system"] }
opentelemetry-proto = { version = "0.31.0", features = ["trace", "gen-tonic"] }
parking_lot = "0.12.5"
ratatui = "0.29.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tonic = { version = "0.14", features = ["transport"] }
tracing = "0.1.44"
